theme: jekyll-theme-cayman
google_analytics: 143024889

github:
  zip_url: http://example.com/download.zip
  Documentation: https://github.com/oeg-upm/Helio/wiki

plugins:
- jekyll-readme-index
- jekyll-sitemap
- jekyll-avatar
