theme: jekyll-theme-cayman
google_analytics: 143024889


show_downloads: true
github:
  repository_url: https://github.com/oeg-upm/helio/wiki

plugins:
- jekyll-readme-index
- jekyll-sitemap
- jekyll-avatar
